CREATE DATABASE IF NOT EXISTS OFFICETASKDATABASE;
USE OFFICETASKDATABASE;

CREATE TABLE IF NOT EXISTS Rooms (
  Id   INT          NOT NULL,
  Name VARCHAR(100) NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS Users (
  Id        INT          NOT NULL AUTO_INCREMENT,
  Login     VARCHAR(100) NOT NULL UNIQUE,
  Password  VARCHAR(100) NOT NULL,
  Role      VARCHAR(45)  NOT NULL,
  FirstName VARCHAR(100) NOT NULL,
  LastName  VARCHAR(100) NOT NULL,
  Email     VARCHAR(100) NOT NULL,
  RoomId    INT,
  PRIMARY KEY (Id),
  FOREIGN KEY (roomId) REFERENCES Rooms (Id)
);


CREATE TABLE IF NOT EXISTS Projects (
  Id   INT,
  Name VARCHAR(100),
  PRIMARY KEY (Id)
);


CREATE TABLE IF NOT EXISTS ProjectsUsers (
  projectId INT NOT NULL,
  userId    INT NOT NULL,
  FOREIGN KEY (projectID) REFERENCES Projects (Id),
  FOREIGN KEY (userId) REFERENCES Users (Id)
);

CREATE TABLE IF NOT EXISTS RoomsUsers (
  roomId INT NOT NULL,
  userId INT NOT NULL,
  FOREIGN KEY (roomId) REFERENCES Rooms (Id),
  FOREIGN KEY (userId) REFERENCES Users (Id)
);

CREATE TABLE IF NOT EXISTS Dates (
  id   INT  NOT NULL,
  date DATE NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS UsersDates (
  dateId INT NOT NULL,
  userId INT NOT NULL,
  FOREIGN KEY (userId) REFERENCES Users (Id),
  FOREIGN KEY (dateId) REFERENCES Users (Id)
);


