CREATE DATABASE IF NOT EXISTS OFFICETASKDATABASE;
USE OFFICETASKDATABASE;

CREATE TABLE IF NOT EXISTS Users (
   Id INT NOT NULL AUTO_INCREMENT,
   Role INT NOT NULL,
   FirstName VARCHAR(100) NOT NULL,
   LastName VARCHAR(100) NOT NULL,
   Email VARCHAR(100) NOT NULL,
   PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS UsersPasswords (
  userId int NOT NULL,
  Login VARCHAR(100) NOT NULL,
  Password VARCHAR(100) NOT NULL,
  FOREIGN KEY (userId) REFERENCES Users(Id)
);


CREATE TABLE IF NOT EXISTS Projects (
  Id INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS Rooms (
  Id INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS ProjectsUsers (
  projectId INT NOT NULL,
  userId int NOT NULL,
  FOREIGN KEY (projectID) REFERENCES Projects(Id),
  FOREIGN KEY (userId) REFERENCES Users(Id)
);

CREATE TABLE IF NOT EXISTS RoomsUsers (
  roomId INT NOT NULL,
  userId INT NOT NULL,
  FOREIGN KEY (roomId) REFERENCES Rooms(Id),
  FOREIGN KEY (userId) REFERENCES Users(Id)
);

CREATE TABLE IF NOT EXISTS UsersDates (
  date DATE NOT NULL,
  userId int NOT NULL,
  FOREIGN KEY (userId) REFERENCES Users(Id)
);


CREATE TABLE IF NOT EXISTS roles (
  Id INT NOT NULL,
  Name VARCHAR(10) NOT NULL

);

INSERT INTO Roles VALUES (0, 'User'), (1, 'Admin');
